# Copyright 2020 LMNT, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

import numpy as np
import os
import torch
import torchaudio

from argparse import ArgumentParser

from diffwave.params import AttrDict, params as base_params
from diffwave.model import DiffWave


models = {}

def predict(input, mask, spectrogram=None, model_dir=None, params=None, device=torch.device('cuda'), fast_sampling=False):
  # Lazy load model.
  if not model_dir in models:
    if os.path.exists(f'{model_dir}/weights.pt'):
      checkpoint = torch.load(f'{model_dir}/weights.pt')
    else:
      checkpoint = torch.load(model_dir)
    model = DiffWave(AttrDict(base_params)).to(device)
    model.load_state_dict(checkpoint['model'])
    model.eval()
    models[model_dir] = model

  model = models[model_dir]
  model.params.override(params)

  with torch.no_grad():
    # Change in notation from the DiffWave paper for fast sampling.
    # DiffWave paper -> Implementation below
    # --------------------------------------
    # alpha -> talpha
    # beta -> training_noise_schedule
    # gamma -> alpha
    # eta -> beta
    training_noise_schedule = np.array(model.params.noise_schedule)
    inference_noise_schedule = np.array(model.params.inference_noise_schedule) if fast_sampling else training_noise_schedule

    talpha = 1 - training_noise_schedule
    talpha_cum = np.cumprod(talpha)

    beta = inference_noise_schedule
    alpha = 1 - beta
    alpha_cum = np.cumprod(alpha)

    T = []
    for s in range(len(inference_noise_schedule)):
      for t in range(len(training_noise_schedule) - 1):
        if talpha_cum[t+1] <= alpha_cum[s] <= talpha_cum[t]:
          twiddle = (talpha_cum[t]**0.5 - alpha_cum[s]**0.5) / (talpha_cum[t]**0.5 - talpha_cum[t+1]**0.5)
          T.append(t + twiddle)
          break
    T = np.array(T, dtype=np.float32)

    # if not model.params.unconditional:
    #   if len(spectrogram.shape) == 2:# Expand rank 2 tensors by adding a batch dimension.
    #     spectrogram = spectrogram.unsqueeze(0)
    #   spectrogram = spectrogram.to(device)
    #   x_t = torch.randn(spectrogram.shape[0], model.params.hop_samples * spectrogram.shape[-1], device=device)
    # else:
    #   x_t = torch.randn(1, params.audio_len, device=device)
    # noise_scale = torch.from_numpy(alpha_cum**0.5).float().unsqueeze(1).to(device)

    # Forward process
    x_0, m = input, mask
    mean = alpha_cum[-1]**0.5 * x_0
    std = (1 - alpha_cum[-1]) * torch.eye(len(alpha_cum))
    x_T = torch.normal(mean, std) # Equation 7 in RePaint

    # Reverse process
    x_t = x_T

    for t in range(len(alpha) - 1, -1, -1):

      # Calculation of x t-1 known
      eps = torch.randn_like(x_0)
      x_tmin1_known = alpha_cum[t]**0.5 * x_0 + (1.0 - alpha_cum[t]) * eps
      x_tmin1_known = torch.clamp(x_tmin1_known, -1.0, 1.0)

      # Calculation of x t-1 unknown
      c1 = 1 / alpha[t]**0.5
      c2 = beta[t] / (1 - alpha_cum[t])**0.5
      x_tmin1_unknown = c1 * (x_t - c2 * model(x_t, torch.tensor([T[t]], device=x_t.device), spectrogram).squeeze(1))
      if t > 0:
        z = torch.randn_like(x_t)
        sigma_t = ((1.0 - alpha_cum[t-1]) / (1.0 - alpha_cum[t]) * beta[t])**0.5
        x_tmin1_unknown += sigma_t * z
      x_tmin1_unknown = torch.clamp(x_tmin1_unknown, -1.0, 1.0)

      # Calculation of x t-1
      x_tmin1 = m * x_tmin1_known + (1 - m) * x_tmin1_unknown
      
      if t > 0:
        mean = (1.0 - beta[t-1])**0.5 * x_tmin1
        std = beta[t-1] * torch.eye(len(x_tmin1))
        x_t = torch.normal(mean, std)

  return x_0, model.params.sample_rate


def main(args):
  if args.spectrogram_path:
    spectrogram = torch.from_numpy(np.load(args.spectrogram_path))
  else:
    spectrogram = None

  input = torch.from_numpy(np.load(args.input_path))
  mask = torch.from_numpy(np.load(args.mask_path))

  audio, sr = predict(input, mask, spectrogram, model_dir=args.model_dir, fast_sampling=args.fast, params=base_params)
  torchaudio.save(args.output, audio.cpu(), sample_rate=sr)


if __name__ == '__main__':
  parser = ArgumentParser(description='runs inference on a spectrogram file generated by diffwave.preprocess')
  parser.add_argument('model_dir',
      help='directory containing a trained model (or full path to weights.pt file)')
  parser.add_argument('--spectrogram_path', '-s',
      help='path to a spectrogram file generated by diffwave.preprocess')
  parser.add_argument('--output', '-o', default='output.wav',
      help='output file name')
  parser.add_argument('--fast', '-f', action='store_true',
      help='fast sampling procedure')
  main(parser.parse_args())
